main: me.eeshe.gtmobs.GTMobs
name: GTMobs
version: ${project.version}
author: Eeshe
depend: [ ViaVersion ]
softdepend: [ PlaceholderAPI, ProtocolLib ]
api-version: 1.13

commands:
  gtmobs:
  packets:
